# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "dey/caliopen_full-ubuntu-14.04"
  config.vm.box_version = "1.0.0"
  config.vm.network :private_network, ip: "192.168.10.10"
  config.vm.synced_folder "./", "/vagrant", owner: "caliopen", group: "caliopen"
  config.vm.provision :shell, path: File.dirname(__FILE__) + "/includes/init-caliopen.sh"
  config.vm.provision :shell, path: File.dirname(__FILE__) + "/includes/link-projects.sh", run: "always"
  config.vm.provision :shell, path: File.dirname(__FILE__) + "/includes/start-caliopen.sh", run: "always"

  # for now cassandra requires at min 2GB  to run cf. https://github.com/CaliOpen/caliopen.web/issues/3#issuecomment-54809578
  config.vm.provider "virtualbox" do |v|
    #   v.cpus = 2
      v.memory = 2048
  end
end
